galaxy_info:
  author: Jaskaranbir Dhillon
  description: Installs PIP3 and necessary Python modules

  license: WTFPL

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
      - 16.04

  galaxy_tags:
    - python
    - pip
