---
# tasks file for roles/setup-python-modules

- name: Install PIP3
  apt: name=python3-pip update_cache=yes

- name: Install requested python-modules
  pip:
    name: "{{ required_python_packages | join(' ') }}"
    state: latest
